spring:
  application:
    name: blueprint-api
  datasource:
    url: jdbc:postgresql://localhost:5432/clean-arch-db
    username: application
    password: application
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true