spring:
  config:
    import: "optional:file:.env[.properties]" # import secrets and config
  application:
    name: pragmatic-clean-architecture
  datasource:
    url: jdbc:postgresql://localhost:5432/${APP_DB_NAME}
    username: ${APP_DB_USERNAME}
    password: ${APP_DB_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true